### ISSUE TITLE
can you share full dataset of facewarehouse or the mean shape, id and expression ?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [phg1024/BlendshapeGeneration#1]
Good job for me!
by the way, can you share full dataset of facewarehouse or the mean shape, id and expression you generate? it is really useful! and i can not get it because teacher zhou protect it recent years. thx~, my email is 18354226160@163.com.

**Comment by ZHANG-SHI-CHANG** [comment]
i get it, thx~. close it

**Comment by skygoo** [comment]
hello.
      Can you share the full dataset of facewarehouse to cskgogo@126.com, This data is urgently needed for me. And it's really hard to apply now。Best wishes.

**Comment by phg1024** [comment]
Sorry - please obtain the data set through its official site http://kunzhou.net/zjugaps/facewarehouse/ since this data is _very personal_.

**Comment by skygoo** [comment]
Got it. This is my forced choice to ask from others after I have send email to apply from official site without any respond .Thanks anyway.
